# Managed by 'wp'. Active theme: carbon-fiber-3
# carbon-fiber-3.png (upscaled + TN 0.25)
# Switch with:  wp set <name>   |   list with:  wp list
wallpaper {
    monitor = DP-6
    path = /home/vidar/ai/wallpaper/wall_DP-6_carbon-fiber-3.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = /home/vidar/ai/wallpaper/wall_DP-5_carbon-fiber-3.png
    fit_mode = cover
}

splash = false
ipc = on
